# Generated by Django 5.0.4 on 2024-05-04 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('price', models.FloatField()),
                ('discount', models.FloatField()),
                ('composition', models.TextField(default='')),
                ('category', models.CharField(choices=[('TS', 'Tshirt'), ('DR', 'Diaries'), ('UM', 'Umbrellas'), ('RL', 'Reflectors'), ('Cp', 'Caps')], max_length=2)),
                ('image', models.ImageField(upload_to='product')),
            ],
        ),
    ]
